### ISSUE TITLE
Text Box updates

### ISSUE THREAD

**Issue by riteshsp2000** [dscnitrourkela/project-icecream#41]
**Is your feature request related to a problem? Please describe.**
As of now, the text shown is sort of static. As in there is no way to change the font family, no way to update background colour, no option to change the shape of the text background shape.

**Describe the solution you'd like**
- Add a colour picker to chose and update the background of the text. (Possible additions for options to chose a gradient - just like Figma, linear, radial, etc)
- A drop down to choose a selected few font families for the text. No need for separate ones for name and guild, a common would do the job.
- The design team could come up with a few shapes as background. So a carousel of shapes to choose from for the text box would be great.

**Comment by Sonakshi1901** [comment]
Interested
